INSERT INTO pance_departamentos VALUES ('0','046','05',NULL,'Antioquia');
INSERT INTO pance_departamentos VALUES ('0','046','08',NULL,'Atlántico');
INSERT INTO pance_departamentos VALUES ('0','046','11',NULL,'Bogotá');
INSERT INTO pance_departamentos VALUES ('0','046','13',NULL,'Bolivar');
INSERT INTO pance_departamentos VALUES ('0','046','15',NULL,'Boyacá');
INSERT INTO pance_departamentos VALUES ('0','046','17',NULL,'Caldas');
INSERT INTO pance_departamentos VALUES ('0','046','18',NULL,'Caquetá');
INSERT INTO pance_departamentos VALUES ('0','046','19',NULL,'Cauca');
INSERT INTO pance_departamentos VALUES ('0','046','20',NULL,'Cesar');
INSERT INTO pance_departamentos VALUES ('0','046','23',NULL,'Córdoba');
INSERT INTO pance_departamentos VALUES ('0','046','25',NULL,'Cundinamarca');
INSERT INTO pance_departamentos VALUES ('0','046','27',NULL,'Chocó');
INSERT INTO pance_departamentos VALUES ('0','046','41',NULL,'Huila');
INSERT INTO pance_departamentos VALUES ('0','046','44',NULL,'La Guajira');
INSERT INTO pance_departamentos VALUES ('0','046','47',NULL,'Magdalena');
INSERT INTO pance_departamentos VALUES ('0','046','50',NULL,'Meta');
INSERT INTO pance_departamentos VALUES ('0','046','52',NULL,'Nariño');
INSERT INTO pance_departamentos VALUES ('0','046','54',NULL,'Norte de Santander');
INSERT INTO pance_departamentos VALUES ('0','046','63',NULL,'Quindío');
INSERT INTO pance_departamentos VALUES ('0','046','66',NULL,'Risaralda');
INSERT INTO pance_departamentos VALUES ('0','046','68',NULL,'Santander');
INSERT INTO pance_departamentos VALUES ('0','046','70',NULL,'Sucre');
INSERT INTO pance_departamentos VALUES ('0','046','73',NULL,'Tolima');
INSERT INTO pance_departamentos VALUES ('0','046','76',NULL,'Valle del Cauca');
INSERT INTO pance_departamentos VALUES ('0','046','81',NULL,'Arauca');
INSERT INTO pance_departamentos VALUES ('0','046','85',NULL,'Casanare');
INSERT INTO pance_departamentos VALUES ('0','046','86',NULL,'Putumayo');
INSERT INTO pance_departamentos VALUES ('0','046','88',NULL,'San Andrés');
INSERT INTO pance_departamentos VALUES ('0','046','91',NULL,'Amazonas');
INSERT INTO pance_departamentos VALUES ('0','046','94',NULL,'Guainía');
INSERT INTO pance_departamentos VALUES ('0','046','95',NULL,'Guaviare');
INSERT INTO pance_departamentos VALUES ('0','046','97',NULL,'Vaupes');
INSERT INTO pance_departamentos VALUES ('0','046','99',NULL,'Vichada');