<?php

/**
*
* Copyright (C) 2008 LinuxCali Ltda
* Francisco J. Lozano B. <pacho@linuxcali.com>
* Mauricio Oidor L. <ozzymauricio75@gmail.com>
*
* Este archivo es parte de:
* PANCE :: Plataforma para la Administración del Nexo Cliente-Empresa
*
* Este programa es software libre: usted puede redistribuirlo y/o
* modificarlo  bajo los términos de la Licencia Pública General GNU
* publicada por la Fundación para el Software Libre, ya sea la versión 3
* de la Licencia, o (a su elección) cualquier versión posterior.
*
* Este programa se distribuye con la esperanza de que sea útil, pero
* SIN GARANTÍA ALGUNA; ni siquiera la garantía implícita MERCANTIL o
* de APTITUD PARA UN PROPÓSITO DETERMINADO. Consulte los detalles de
* la Licencia Pública General GNU para obtener una información más
* detallada.
*
* Debería haber recibido una copia de la Licencia Pública General GNU
* junto a este programa. En caso contrario, consulte:
* <http://www.gnu.org/licenses/>.
*
**/

$textos = array(
    "GESTCOCL"                                   => "Cotizaciones",
    "EXPOCOTI"                                   => "Exportar cotización",
    "APROCOTI"                                   => "Aprobar cotización",
    "ANULCOTI"                                   => "Anular cotización",
    "REPLCOTI"                                   => "Reemplazar cotización",
    "RECOCOTI"                                   => "Recotizar cotización",
    "REPOCOTI"                                   => "Reporte cotización",
    "EJECCOTI"                                   => "Ejecutar cotización",
    "EXPORTAR"                                   => "Exportar",
    "APROBAR"                                    => "Aprobar",
    "ANULAR"                                     => "Descartar",
    "REEMPLAZAR"                                 => "Reemplazar",
    "RECOTIZAR"                                  => "Recotizar",
    "EJECUTAR"                                   => "Ejecutada",
    "ENVIAR"                                     => "Enviar",
    "IMPRIMIR_PDF"                               => "Descargar PDF",
    "PENDIENTE"                                  => "Pendiente",
    "APROBADA"                                   => "Aprobada",
    "ANULADA"                                    => "Anulada",
    "COTIZADA"                                   => "Cotizada",
    "NUMERO_REQUERIMIENTO"                       => "Numero requerimiento",
    "NUMERO_CONTRATO"                            => "Numero contrato",
    "NUMERO_POLIZA"                              => "Numero póliza",
    "CONTRATO"                                   => "Contrato",
    "POLIZA"                                     => "Póliza",
    "ASUNTO"                                     => "Asunto",
    "TEMA_ASUNTO"                                => "Cotización requerimiento",
    "ATTE"                                       => "Señor(a)",
    "TITULO"                                     => "Atentos a su amable invitación, nos permitimos poner bajo su consideración la presente propuesta relacionada con el requerimiento solicitado.",
    "TITULO_2"                                   => "Esperamos que nuestra propuesta sea de su total agrado esperando que tomen ustedes la decisión más acertada para dar cumplimiento a sus necesidades.",
    "SALUDO"                                     => "Cordial saludo",
    "CORDIALMENTE"                               => "Cordialmente,",
    "id"                                         => "Código cotización",
    "EMPRESA"                                    => "Empresa",
    "SEDE"                                       => "Sede",
    "SUCURSAL"                                   => "Consorciado",
    "MUNICIPIO"                                  => "Municipio",
    "ESTADO"                                     => "Estado",
    "ESTADO_COTIZACION"                          => "Estado cotización",
    "ESTADO_COTIZACION_CLIENTE"                  => "Estado cliente",
    "ESTADO_CONSORCIADO"                         => "Estado consorciado",
    "TIPO_SOLICITUD"                             => "Tipo solicitud",
    "OBSERVACIONES"                              => "Observaciones generadas por el cliente",
    "OBSERVACIONES_VISITA"                       => "Observaciones visita",
    "OBSERVACIONES_APROBACION"                   => "Observaciones aprobación",
    "FECHA_VISITA"                               => "Fecha visita",
    "FECHA_INGRESO"                              => "Fecha ingreso",
    "NUMERO_COTIZACION"                          => "Cotización",
    "CONSECUTIVO_COTIZACION"                     => "Cons.",
    "AYUDA_CONSECUTIVO_COTIZACION"               => "Consecutivo para la nueva cotización",
    "NUMERO_COTIZACION_CONSORCIADO"              => "Numero cotización consorciado",
    "VALOR_REQUERIMIENTO"                        => "Valor requerimiento",
    "VALOR_BASE_IMPUESTO"                        => "Valor base para impuesto",
    "VALOR_MANO_OBRA_COTIZACION"                 => "Valor mano de obra",
    "VALOR_MANO_OBRA_MODIFICADA"                 => "Valor mano de obra propuesto",
    "VALOR_MATERIALES_COTIZACION"                => "Valor materiales",
    "VALOR_MATERIALES_MODIFICADO"                => "Valor materiales propuesto",
    "VALOR_ADMINISTRACION_COTIZACION"            => "Valor administración",
    "VALOR_IMPREVISTOS_COTIZACION"               => "Valor imprevistos",
    "VALOR_UTILIDAD"                             => "Valor utilidad",
    "VALOR_IMPUESTO"                             => "Valor impuesto",
    "VALOR_ANTICIPO"                             => "Valor anticipo",
    "SUB_TOTAL"                                  => "Sub-Total",
    "TOTAL_GENERAL"                              => "Total general",
    "PORCENTAJE_ADMINISTRACION_COTIZACION"       => "Porcentaje admin",
    "PORCENTAJE_ADMINISTRACION_MODIFICADO"       => "Porcentaje admin propuesto",
    "PORCENTAJE_IMPREVISTOS_COTIZACION"          => "Porcentaje imprevisto",
    "PORCENTAJE_IMPREVISTOS_MODIFICADO"          => "Porcentaje imprevisto propuesto",
    "COSTO_DIRECTO"                              => "Costo directo",
    "COSTO_DIRECTO_MODIFICADO"                   => "Costo directo propuesto",
    "PORCENTAJE_UTILIDAD"                        => "Porcentaje utilidad",
    "PORCENTAJE_UTILIDAD_MODIFICADA"             => "Porcentaje utilidad propuesto",
    "IMPUESTO"                                   => "Impuesto",
    "BASE_IMPUESTO"                              => "Base para impuesto",
    "VALOR_BASE"                                 => "Valor base",
    "IMPUESTO_MODIFICADO"                        => "Impuesto propuesto",
    "FORMA_PAGO"                                 => "Forma de pago",
    "FORMA_PAGO_MODIFICADO"                      => "Forma de pago propuesta",
    "PORCENTAJE_ANTICIPO"                        => "Porcentaje anticipo",
    "PORCENTAJE_ANTICIPO_MODIFICADO"             => "Porcentaje anticipo propuesto",
    "PORCENTAJE_MANO_OBRA"                       => "Porcentaje mano obra",
    "PORCENTAJE_MANO_OBRA_MODIFICADO"            => "Porcentaje mano obra propuesto",
    "PORCENTAJE_MATERIALES"                      => "Porcentaje materiales",
    "PORCENTAJE_MATERIALES_MODIFICADO"           => "Porcentaje materiales propuesto",
    "FECHA_ENVIO"                                => "Fecha envío cotización",
    "NOMBRE_SEDE"                                => "Sede",
    "NOMBRE_CONTACTO"                            => "Contacto",
    "TERCERO"                                    => "Empresa",
    "PAGO_PARCIAL"                               => "Pago parcial",
    "CONTRAENTREGA"                              => "Contra-Entrega",
    "RAZON_SOCIAL"                               => "Razón social",
    "CONTACTO"                                   => "Contacto",
    "CODIGO"                                     => "Código sede",
    "SEDE"                                       => "Sede",
    "CARGO"                                      => "Cargo",
    "TIPO_SOLICITUD"                             => "Tipo solicitud",
    "FECHA_APROBACION"                           => "Fecha aprobación",
    "FECHA_ENVIO"                                => "Fecha envío",
    "FECHA_LIMITE_VISITA"                        => "Limite visita",    
    "FECHA_INGRESO_SISTEMA"                      => "Fecha - hora confirmación",
    "DESCRIPCION"                                => "Descripción ",
    "OBSERVACIONES"                              => "Observaciones",
    "CONFIRMADO"                                 => "Confirmada",
    "NO_CONFIRMADO"                              => "No confirmada",
    "COTIZADA"                                   => "Cotizar",
    "NO_COTIZADA"                                => "No cotizar",
    "TELEFONO_PRINCIPAL"                         => "Teléfono principal",
    "CELULAR"                                    => "Celular",
    "MANTENIMIENTO"                              => "Mantenimiento",
    "EMERGENCIA"                                 => "Emergencia",
    "SERVICIO"                                   => "Servicio por demanda",
    "PROYECTO"                                   => "Proyecto",
    "VISITA"                                     => "Visita",
    "AIU"                                        => "AIU",
    "NO_AIU"                                     => "No AIU",
    "NO_ENVIADA"                                 => "No enviada",
    "ENVIADA"                                    => "Enviada",
    "APROBADA"                                   => "Aprobada",
    "NO_APROBADA"                                => "No aprobada",
    "ITEM_ANULADO"                               => "Anulada",
    "CORREO_ELECTRONICO"                         => "Correo electrónico",
    "PESTANA_COTIZACION"                         => "Datos cotización",
    "PESTANA_REQUERIMIENTO"                      => "Información requerimiento",
    "PESTANA_DATOS_CONTROL"                      => "Datos control",
    "PESTANA_REEMPLAZAR"                         => "Cotizaciones nuevas",
    "AYUDA_NUMERO_COTIZACION"                    => "Numero cotización",
    "AYUDA_CONTRATO"                             => "Numero de contrato para el proyecto",
    "AYUDA_POLIZA"                               => "Numero de póliza para el proyecto",
    "AYUDA_BASE_IMPUESTO"                        => "Valor base para impuesto",
    "AYUDA_NUMERO_COTIZACION_CONSORCIADO"        => "Numero cotización consorciado",
    "AYUDA_IMPUESTO"                             => "Valor del impuesto sobre la utilidad",
    "AYUDA_SUCURSAL"                             => "Sucursal asignada a la sede",
    "AYUDA_CODIGO"                               => "Código asignado a la sede",
    "AYUDA_SEDE"                                 => "Sede que realizara la solicitud",
    "AYUDA_EMPRESA"                              => "Empresa del consorcio",
    "AYUDA_FECHA_INGRESO"                        => "Fecha de solicitud del servicio",
    "AYUDA_FECHA_VISITA"                         => "Fecha visita",
    "AYUDA_FECHA_ENVIO"                          => "Fecha envío de la cotización al cliente",
    "AYUDA_FECHA_APROBACION"                     => "Fecha de aprobacion de la cotización",
    "AYUDA_DESCRIPCION"                          => "Descripción del servicio",
    "AYUDA_TIPO_SOLICITUD"                       => "Tipo de servicio solicitado",
    "AYUDA_SUCURSAL"                             => "Nombre de la sucursal del consorcio",
    "AYUDA_TERCERO"                              => "Empresa asignada al servicio",
    "AYUDA_CONTACTO"                             => "Persona a contactar",
    "AYUDA_CARGO"                                => "Cargo que ocupa la persona a contactar",
    "AYUDA_ESTADO"                               => "Estado de la solicitud",
    "AYUDA_CORREO_ELECTRONICO"                   => "Correo electrónico de la persona a contactar",
    "AYUDA_TELEFONO_PRINCIPAL"                   => "Teléfono principal de la persona a contactar",
    "AYUDA_CELULAR"                              => "Numero celular de la persona a contactar",
    "AYUDA_OBSERVACIONES"                        => "Indicaciones adicionales dadas por el cliente",
    "AYUDA_OBSERVACIONES_VISITA"                 => "Observaciones hechas en la visita por el consorciado",
    "AYUDA_OBSERVACIONES_APROBACION"             => "Observaciones hechas en la aprobacion de la cotización",
    "AYUDA_VALOR_MANO_OBRA_COTIZACION"           => "Valor de la mano de obra del requerimiento",
    "AYUDA_VALOR_MANO_OBRA_MODIFICADA"           => "Valor de la mano de obra propuesto",
    "AYUDA_VALOR_MATERIALES_COTIZACION"          => "Valor de los materiales del requerimiento",
    "AYUDA_VALOR_MATERIALES_MODIFICADO"          => "Valor de los materiales propuesto",
    "AYUDA_PORCENTAJE_ADMINISTRACION_COTIZACION" => "Porcentaje de Administración",
    "AYUDA_PORCENTAJE_ADMINISTRACION_MODIFICADO" => "Porcentaje de Administración propuesto",
    "AYUDA_PORCENTAJE_IMPREVISTOS_COTIZACION"    => "Porcentaje de los imprevistos",
    "AYUDA_PORCENTAJE_IMPREVISTOS_MODIFICADO"    => "Porcentaje de los imprevistos propuesto",
    "AYUDA_COSTO_DIRECTO"                        => "Costo directo requerimiento",
    "AYUDA_COSTO_DIRECTO_MODIFICADO"             => "Costo directo propuesto",
    "AYUDA_PORCENTAJE_UTILIDAD"                  => "Porcentaje de la utilidad",
    "AYUDA_PORCENTAJE_UTILIDAD_MODIFICADA"       => "Porcentaje de la utilidad propuesto",
    "AYUDA_IMPUESTO"                             => "Porcentaje del impuesto sobre la utilidad",
    "AYUDA_IMPUESTO_MODIFICADO"                  => "Valor del impuesto sobre la utilidad propuesto por el cliente",
    "AYUDA_VALOR_ADMINISTRACION_COTIZACION"      => "Valor administración calculado",
    "AYUDA_VALOR_IMPREVISTOS_COTIZACION"         => "Valor imprevistos calculado",
    "AYUDA_VALOR_UTILIDAD"                       => "Valor utilidad calculado",
    "AYUDA_VALOR_IMPUESTO"                       => "Valor impuesto calculado",
    "AYUDA_FORMA_PAGO"                           => "Forma de pago del requerimiento",
    "AYUDA_FORMA_PAGO_MODIFICADO"                => "Forma de pago propuesto",
    "AYUDA_PORCENTAJE_ANTICIPO"                  => "Porcentaje sobre el valor total para el anticipo",
    "AYUDA_PORCENTAJE_ANTICIPO_MODIFICADO"       => "Porcentaje sobre el valor total para el anticipo propuesto",
    "AYUDA_PORCENTAJE_MANO_OBRA"                 => "Porcentaje correspondiente al consorciado por mano de obra",
    "AYUDA_PORCENTAJE_MATERIALES"                => "Porcentaje correspondiente al consorciado por materiales",
    "AYUDA_ESTADO_COTIZACION_CLIENTE"            => "Verificar que se envió al cliente la cotización",
    "AYUDA_SUB_TOTAL"                            => "Sub-Total",
    "AYUDA_TOTAL_GENERAL"                        => "Total general",
    "ERROR_MODIFICAR_COTIZAR"                    => "La cotización no ha sido generada o enviada al cliente",
    "ERROR_ELIMINAR_COTIZAR"                     => "La cotización no es posible eliminarla, por favor debe generarla",
    "ERROR_EXISTE_DESCRIPCION"                   => "Ya existe esa descripción del requerimiento",
    "ERROR_EXISTE_SEDE"                          => "Ya existe una sede con ese código",
    "ERROR_EXISTE_NUMERO_COTIZACION"             => "Ya existe ese numero de cotización",
    "ERROR_EXISTE_CONTACTO"                      => "Ya existe un contacto con ese nombre",
    "ERROR_EXISTE_CODIGO"                        => "Ya existe un requerimiento con ese código",
    "ERROR_FORMATO_NUMERO_COTIZACION"            => "El numero de la cotización debe contener solo números",
    "ERROR_FORMATO_MANO_OBRA"                    => "El campo mano de obra debe contener solo números",
    "ERROR_FORMATO_MATERIALES"                   => "El campo materiales debe contener solo números",
    "ERROR_FORMATO_PORCENTAJE_ANTICIPO"          => "El campo anticipo debe contener solo números",
    "ERROR_FORMATO_PORCENTAJE_MANO_OBRA"         => "El campo porcentaje de la mano de obra debe contener solo números",
    "ERROR_FORMATO_PORCENTAJE_MATERIALES"        => "El campo porcentaje materiales debe contener solo números",
    "ERROR_FORMATO_ADMINISTRACION"               => "El campo valor administración debe contener solo números",
    "ERROR_FORMATO_IMPREVISTOS"                  => "El campo imprevistos debe contener solo números",
    "ERROR_FORMATO_UTILIDAD"                     => "El campo utilidad debe contener solo números",
    "ERROR_FORMATO_IMPUESTO"                     => "El campo impuesto debe contener solo números",
    "ERROR_APROBAR_ITEM_COTIZADO"                => "No se pudo aprobar cotización",
    "ERROR_APROBACION_COTIZACION"                => "La cotización no ha sido aprobada",
    "ERROR_ENVIANDO_ITEM"                        => "Error, cotización ejecutada",
    "ITEM_APROBADO"                              => "Cotización aprobada",
    "ITEM_ENVIADO"                               => "Cotización enviada",
    "TELEFONO_CONTACTO"                          => "Telefono del contacto",
    "CODIGO_CONTABLE"                            => "Codigo contable",
    "PERSONA_RECIBE"                             => "Persona recibio requerimiento",
    "MEDIO_RECIBO"                               => "Medio de recibo del requerimiento",
    "COTIZACION_NO_APROBADA"                     => "Cotización no ha sido aprobada",
    "COTIZACION_DECARTADA"                       => "Cotización fue descartada",
    "COTIZACION_FACTURADA"                       => "Cotización facturada",
    "COTIZACION_EJECUTADA"                       => "Cotización ya fue ejecutada",
    "OTRA_COTIZACION"                            => "Cotización fue reemplazada ó recotizada",
    "ERROR_ANULAR"                               => "Cotizacion con movimiento ó ya fue descartada",
    "ERROR_APROBAR_ITEM"                         => "Cotización ya fue aprobada ó tiene movimiento",
    "TIPO_ACTA"                                  => "Tipo acta",
    "FECHA_ACTA"                                 => "Fecha acta",
    "PORCENTAJE_MANO_OBRA"                       => "% Mano obra",
    "PORCENTAJE_MATERIALES"                      => "% Materiales",
    "VALOR_ACTA"                                 => "Valor acta",
    "FACTURA_CLIENTE"                            => "Factura cliente",
    "VALOR_CLIENTE"                              => "Valor CIMCO",
    "FACTURA_CONSORCIADO"                        => "Factura consorciado",
    "VALOR_CONSORCIADO"                          => "Valor consorciado",
    "VALOR_ADMINISTRACION"                       => "Valor administracion",
    "PESTANA_ACTAS"                              => "Actas",
    "SELECCIONAR_TODOS"                          => "Seleccionar todos",
    "CONSORCIADOS"                               => "Consorciados",
    "ERROR_FECHAS"                               => "Fecha hasta menor que fecha desde",
    "PENDIENTE"                                  => "Pendiente",
    "EJECUCION"                                  => "En ejecución",
    "DESCARTADA"                                 => "Descartada",
    "FACTURADA_TOTAL"                            => "Facturada total", 
    "FACTURADA_PARCIAL"                          => "Facturada parcial",
    "EJECUTADA"                                  => "Ejecutada",
    "REEMPLAZADA"                                => "Reemplazada",
    "RECOTIZADA"                                 => "Recotizada",
    "ABRIR_PLANO"                                => "Descargar archivo",
    "TODOS"                                      => "Todos",
    "AYUDA_FECHA_DESDE"                          => "Fecha inicio del reporte",
    "AYUDA_FECHA_HASTA"                          => "Fecha final del reporte",
    "PESTANA_REPORTE"                            => "Archivo plano",
    "GENERAR_PLANO"                              => "Generar plano",
    "REPOACTA"                                   => "Reporte requerimientos",
    "REQUERIMIENTO"                              => "Requerimiento",
    "REQUERIMIENTO_VISITADO"                     => "Visitado",
    "REQUERIMIENTO_NO_VISITA"                    => "No genero cotización",
    "ACTA_INICIO"                                => "Acta inicio", 
    "ACTA_AVANCE_OBRA"                           => "Acta avance obra",
    "ACTA_FINALIZACION"                          => "Acta finalización",
    "ERROR_SIN_PRIVILEGIO"                       => "Usuario sin privilegios"
);
?>
