<?php

/**
*
* Copyright (C) 2009 FELINUX Ltda
* Francisco J. Lozano B. <fjlozano@felinux.com.co>
* Mauricio Oidor L. <ozzymauricio75@gmail.com>
*
* Este archivo es parte de:
* PANCE :: Plataforma para la Administración del Nexo Cliente-Empresa
*
* Este programa es software libre: usted puede redistribuirlo y/o
* modificarlo  bajo los términos de la Licencia Pública General GNU
* publicada por la Fundación para el Software Libre, ya sea la versión 3
* de la Licencia, o (a su elección) cualquier versión posterior.
*
* Este programa se distribuye con la esperanza de que sea útil, pero
* SIN GARANTÍA ALGUNA; ni siquiera la garantía implícita MERCANTIL o
* de APTITUD PARA UN PROPÓSITO DETERMINADO. Consulte los detalles de
* la Licencia Pública General GNU para obtener una información más
* detallada.
*
* Debería haber recibido una copia de la Licencia Pública General GNU
* junto a este programa. En caso contrario, consulte:
* <http://www.gnu.org/licenses/>.
*
**/

$textos = array(
    "GESTRECL"                             => "Requerimiento clientes",
    "ADICRECL"                             => "Adicionar requerimiento",
    "CONSRECL"                             => "Consultar requerimiento",
    "MODIRECL"                             => "Modificar requerimiento",
    "REPORECL"                             => "Reporte requerimiento",
    "ELIMRECL"                             => "Eliminar requerimiento",
    "NOTIRECL"                             => "Notificar",
    "NOTIFICAR"                            => "Notificar",
    "IMPRIMIR_PDF"                         => "Descargar PDF",
    "id"                                   => "Código requerimiento",
    "CONSECUTIVO"                          => "Número",
    "NOMBRE_SEDE"                          => "Sede",
    "EMPRESA"                              => "Empresa",
    "RAZON_SOCIAL"                         => "Razón social",
    "SUCURSAL"                             => "Consorciado",
    "CONTACTO"                             => "Contacto",
    "TELEFONO_CONTACTO"                    => "Telefono contacto",
    "CODIGO"                               => "Código sede",
    "CODIGO_CONTABLE"                      => "Código contable",
    "SEDE"                                 => "Sede",
    "CARGO"                                => "Cargo",
    "TIPO_SOLICITUD"                       => "Solicitud",
    "ESTADO_CONSORCIADO"                   => "Estado consorciado",
    "FECHA_LIMITE_VISITA"                  => "Limite visita",
    "FECHA_INGRESO"                        => "Ingreso",
    "FECHA_INGRESO_SISTEMA"                => "Fecha - hora confirmación",
    "DESCRIPCION"                          => "Descripción ",
    "EMPRESA"                              => "Empresa",
    "OBSERVACIONES"                        => "Observaciones",
    "COTIZADO"                             => "Cotizado",
    "NOTIFICADO"                           => "Notificado",
    "NO_NOTIFICADO"                        => "No notificado",
    "ESTADO"                               => "Estado solicitud",
    "ESTADO_COTIZACION"                    => "Estado cotización",
    "ESTADO_REQUERIMIENTO"                 => "Estado requerimiento",    
    "AYUDA_ESTADO_REQUERIMIENTO"           => "Seleccione el estado del requerimiento",    
    "TELEFONO_PRINCIPAL"                   => "Teléfono principal",
    "CELULAR"                              => "Celular",
    "MANTENIMIENTO"                        => "Mantenimiento",
    "EMERGENCIA"                           => "Emergencia",
    "SERVICIO"                             => "Servicio por demanda",
    "PROYECTO"                             => "Proyecto",
    "VISITA"                               => "Visita",
    "CORREO_ELECTRONICO"                   => "Correo electrónico",
    "PERSONA_RECIBE"                       => "Persona que recibe",
    "AYUDA_PERSONA_RECIBE"                 => "Nombre de la persona que recibio el requerimiento",
    "MEDIO_RECIBO"                         => "Medio",
    "AYUDA_MEDIO_RECIBO"                   => "Medio por el cual se recibio el requerimiento (Telefono, Correo, etc)",
    "PESTANA_GENERAL"                      => "Información general",
    "PESTANA_COTIZACION"                   => "Cotización",
    "PESTANA_CONTACTO"                     => "Datos de comunicación",
    "MUNICIPIO"                            => "Ubicación",
    "UBICACION_SEDE"                       => "Ubicación",
    "AYUDA_SUCURSAL"                       => "Sucursal asignada a la sede",
    "AYUDA_CONTACTO"                       => "Contacto del requerimiento",
    "AYUDA_ID"                             => "Código requerimiento",
    "AYUDA_SEDE"                           => "Sede relacionada con la empresa",
    "AYUDA_CODIGO"                         => "Código asignado a la sede",
    "AYUDA_CODIGO_CONTABLE"                => "Código contable para el requerimiento",
    "AYUDA_NOMBRE_SEDE"                    => "Sede que realizara la solicitud",
    "AYUDA_EMPRESA"                        => "Empresa del consorcio",
    "AYUDA_FECHA_INGRESO"                  => "Fecha de solicitud del servicio",
    "AYUDA_FECHA_LIMITE_VISITA"            => "Fecha limite de la visita",
    "AYUDA_DESCRIPCION"                    => "Descripción del servicio",
    "AYUDA_TIPO_SOLICITUD"                 => "Tipo de servicio solicitado",
    "AYUDA_SUCURSAL"                       => "Nombre de la sucursal del consorcio",
    "AYUDA_TERCERO"                        => "Empresa asignada al servicio",
    "AYUDA_CONTACTO"                       => "Persona a contactar",
    "AYUDA_TELEFONO_CONTACTO"              => "Telefono persona a contactar",
    "AYUDA_CARGO"                          => "Cargo que ocupa la persona a contactar",
    "AYUDA_OBSERVACIONES"                  => "Indicaciones adicionales dadas por el cliente",
    "AYUDA_ESTADO"                         => "Estado de la solicitud",
    "AYUDA_CONSORCIADO"                    => "Estado del consorciado si ha sido notificado o no",
    "AYUDA_CORREO_ELECTRONICO"             => "Correo electrónico de la persona a contactar",
    "AYUDA_TELEFONO_PRINCIPAL"             => "Teléfono principal de la persona a contactar",
    "AYUDA_CELULAR"                        => "Numero celular de la persona a contactar",
    "ERROR_EXISTE_DESCRIPCION"             => "Ya existe esa descripción del requerimiento",
    "ERROR_EXISTE_SEDE"                    => "Ya existe una sede con ese código",
    "ERROR_EXISTE_CONTACTO"                => "Ya existe un contacto con ese nombre",
    "ERROR_EXISTE_CODIGO"                  => "Ya existe un requerimiento con ese código",
    "ERROR_FORMATO_CODIGO"                 => "El código debe contener solo números",
    "ERROR_REQUERIMIENTO"                  => "No es posible modificar el requerimiento, se encuentra notificado al consorciado",
    "REQUERIMIENTO_COTIZADO"               => "Requerimiento cotizado, no se puede realizar cambios",
    "REQUERIMIENTO_VISITA"                 => "Requerimiento tuvo visita, no se puede realizar cambios",
    "REQUERIMIENTO_SIN_COTIZACION"         => "Requerimiento tuvo visita pero no genero cotizacion, no se puede realizar cambios",
    "VALOR_BASE"                           => "Valor base",
    "SIMBOLO_PORCENTAJE"                   => "%",
    "SIMBOLO_PESO"                         => "$",
    "PORCENTAJE_IMPREVISTOS_COTIZACION"    => "Porcentaje imprevistos",
    "PORCENTAJE_ADMINISTRACION_COTIZACION" => "Porcentaje administracion",
    "VALOR_IMPREVISTOS_COTIZACION"         => "Costo imprevistos",
    "VALOR_ADMINISTRACION_COTIZACION"      => "Costo administracion",
    "PORCENTAJE_UTILIDAD"                  => "Porcentaje utilidad",
    "VALOR_UTILIDAD"                       => "Costo utilidad",
    "NUMERO_COTIZACION"                    => "Número cotización",
    "NUMERO_COTIZACION_CONSORCIADO"        => "Número cotización consorciado",
    "FECHA_VISITA"                         => "Fecha de visita",
    "OBSERVACIONES_VISITA"                 => "Observación visita",
    "VALOR_MANO_OBRA_COTIZACION"           => "Valor mano de obra",
    "VALOR_MATERIALES_COTIZACION"          => "Valor materiales",
    "COSTO_DIRECTO"                        => "Costo directo",
    "BASE_IMPUESTO"                        => "Base para impuesto",
    "IMPUESTO"                             => "Impuesto",
    "VALOR_IMPUESTO"                       => "Valor impuesto",
    "SUB_TOTAL"                            => "Subtotal AIU",
    "TOTAL_GENERAL"                        => "Total",
    "PORCENTAJE_ANTICIPO"                  => "Porcentaje anticipo",
    "VALOR_ANTICIPO"                       => "Valor anticipo",
    "ITEM_ENVIADO"                         => "Enviado",
    "ERROR_PRIVILEGIOS_SEDES"              => "Sin privilegios para sedes",
    "ERROR_PRIVILEGIOS_USUARIO"            => "Usuario sin privilegios",
    "CONTRATO"                             => "Contrato",
    "POLIZA"                               => "Poliza",
    "COSTO_IMPREVISTOS"                    => "Imprevistos",
    "COSTO_ADMINISTRACION"                 => "Administracion",
    "COSTO_UTILIDAD"                       => "Utilidad",
    "MANO_OBRA"                            => "Mano de obra",
    "MATERIALES"                           => "Materiales",
    "COSTO_IMPUESTO"                       => "Impuesto",
    "FECHA_COTIZACION"                     => "Fecha",
    "TIPO_ACTA"                            => "Tipo acta",
    "FECHA_ACTA"                           => "Fecha acta",
    "PORCENTAJE_MANO_OBRA"                 => "% Mano obra",
    "PORCENTAJE_MATERIALES"                => "% Materiales",
    "VALOR_ACTA"                           => "Valor acta",
    "FACTURA_CLIENTE"                      => "Factura cliente",
    "VALOR_CLIENTE"                        => "Valor CIMCO",
    "FACTURA_CONSORCIADO"                  => "Factura consorciado",
    "VALOR_CONSORCIADO"                    => "Valor consorciado",
    "VALOR_ADMINISTRACION"                 => "Valor administracion",
    "PESTANA_ACTAS"                        => "Actas",
    "SELECCIONAR_TODOS"                    => "Seleccionar todos",
    "CONSORCIADOS"                         => "Consorciados",
    "ERROR_FECHAS"                         => "Fecha hasta menor que fecha desde",
    "PENDIENTE"                            => "Pendiente",
    "EJECUCION"                            => "En ejecución",
    "DESCARTADA"                           => "Descartada",
    "FACTURADA_TOTAL"                      => "Facturada total", 
    "FACTURADA_PARCIAL"                    => "Facturada parcial",
    "EJECUTADA"                            => "Ejecutada",
    "REEMPLAZADA"                          => "Reemplazada",
    "RECOTIZADA"                           => "Recotizada",
    "ABRIR_PLANO"                          => "Descargar archivo",
    "TODOS"                                => "Todos",
    "AYUDA_FECHA_DESDE"                    => "Fecha inicio del reporte",
    "AYUDA_FECHA_HASTA"                    => "Fecha final del reporte",
    "PESTANA_REPORTE"                      => "Archivo plano",
    "GENERAR_PLANO"                        => "Generar plano",
    "REPOACTA"                             => "Reporte requerimientos",
    "REQUERIMIENTO"                        => "Requerimiento",
    "REQUERIMIENTO_VISITADO"               => "Visitado",
    "REQUERIMIENTO_NO_VISITA"              => "No genero cotización",
    "ACTA_INICIO"                          => "Acta inicio", 
    "ACTA_AVANCE_OBRA"                     => "Acta avance obra",
    "ACTA_FINALIZACION"                    => "Acta finalización"
);
?>
