INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AF', 'Afganistán');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AL', 'Albania');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'DE', 'Alemania');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AD', 'Andorra');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AO', 'Angola');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AI', 'Anguilla');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AQ', 'Antartida');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AG', 'Antigua y Barbuda');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AN', 'Antillas Holandesas');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SA', 'Arabia Saudí');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'DZ', 'Argelia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AR', 'Argentina');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AM', 'Armenia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AW', 'Aruba');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AU', 'Australia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AT', 'Austria');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AZ', 'Azerbaiyán');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BS', 'Bahamas');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BH', 'Bahrein');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BD', 'Bangladesh');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BB', 'Barbados');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BY', 'Bielorrusia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BE', 'Bélgica');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BZ', 'Belice');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BJ', 'Benin');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BM', 'Bermuda');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BT', 'Bhutan');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BO', 'Bolivia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BA', 'Bosnia y Herzegovina');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BW', 'Botswana');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BR', 'Brasil');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BN', 'Brunei');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BG', 'Bulgaria');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BF', 'Burkina Faso');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BI', 'Burundi');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CV', 'Cabo Verde');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'KH', 'Camboya');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CM', 'Camerún');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CA', 'Canadá');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TD', 'Chad');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CZ', 'Chequia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CL', 'Chile');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CN', 'China continental');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CY', 'Chipre');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'VA', 'Ciudad del Vaticano');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CO', 'Colombia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'KM', 'Comoros');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CG', 'Congo');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CD', 'República Democrática del Congo');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'KR', 'Corea del Sur');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'KP', 'Corea del Norte');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CI', 'Costa de Marfil');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CR', 'Costa Rica');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'HR', 'Croacia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CU', 'Cuba');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'DK', 'Dinamarca');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'DJ', 'Djibouti');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'DM', 'Dominica');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'EC', 'Ecuador');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'EG', 'Egipto');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SV', 'El Salvador');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AE', 'Emiratos Árabes Unidos');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'ER', 'Eritrea');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SK', 'Eslovaquia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SI', 'Eslovenia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'ES', 'España');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'US', 'Estados Unidos');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'EE', 'Estonia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SJ', 'Islas Svalbard y Jan Mayen');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'ET', 'Etiopía');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'FJ', 'Fiji');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'PH', 'Filipinas');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'FI', 'Finlandia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'FR', 'Francia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GA', 'Gabón');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GM', 'Gambia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GS', 'Georgia del Sur e Islas Sandwich del Sur');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GE', 'Georgia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GH', 'Ghana');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GI', 'Gibraltar');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GD', 'Granada');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GR', 'Grecia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GL', 'Groenlandia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GP', 'Guadalupe');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GU', 'Guam');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GT', 'Guatemala');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GY', 'Guyana');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GN', 'Guinea');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GW', 'Guinea-Bissau');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GQ', 'Guinea Ecuatorial');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GF', 'Guyana Francesa');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'HT', 'Haití');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'NL', 'Holanda');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'HN', 'Honduras');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'HK', 'Hong Kong');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'HU', 'Hungría');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'IN', 'India');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'ID', 'Indonesia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'IQ', 'Irak');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'IR', 'Irán');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'IE', 'Irlanda');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'BV', 'Isla Bouvet');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CX', 'Isla Christmas');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'IS', 'Islandia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'KY', 'Islas Caimán');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CC', 'Islas Cocos');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CK', 'Islas Cook');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MP', 'Islas Marianas');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'FO', 'Islas Faroe');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'HM', 'Islas Heard y McDonald');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AX', 'Islas Åland');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'FK', 'Islas Malvinas');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MH', 'Islas Marshall');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'NF', 'Islas Norfolk');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SB', 'Islas Salomón');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TC', 'Islas Turcas y Caicos');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'UM', 'Islas Ultramarinas de Estados Unidos');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'VG', 'Islas Vírgenes Británicas');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'VI', 'Islas Vírgenes de los Estados Unidos');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'IL', 'Israel');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'IT', 'Italia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'JM', 'Jamaica');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'JP', 'Japón');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'JO', 'Jordania');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'KZ', 'Kazajstán');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'KE', 'Kenia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'KG', 'Kirguistán');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'KI', 'Kiribati');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'KW', 'Kuwait');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'LA', 'Laos');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'LS', 'Lesoto');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'LV', 'Letonia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'LB', 'Líbano');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'LR', 'Liberia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'LY', 'Libia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'LI', 'Liechtenstein');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'LT', 'Lituania');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'LU', 'Luxemburgo');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MO', 'Macao');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MK', 'Macedonia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MG', 'Madagascar');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MY', 'Malasia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MW', 'Malawi');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MV', 'Maldivas');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'ML', 'Mali');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MT', 'Malta');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MA', 'Marruecos');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MQ', 'Martinica');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MU', 'Mauricio');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MR', 'Mauritania');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'YT', 'Mayotte');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MX', 'México');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MM', 'Myanmar');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'FM', 'Micronesia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MD', 'Moldavia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MC', 'Mónaco');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MN', 'Mongolia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MS', 'Montserrat');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'MZ', 'Mozambique');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'NA', 'Namibia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'NR', 'Nauru');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'NP', 'Nepal');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'NI', 'Nicaragua');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'NE', 'Níger');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'NG', 'Nigeria');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'NU', 'Niue');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'NO', 'Noruega');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'NC', 'Nueva Caledonia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'NZ', 'Nueva Zelanda');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'OM', 'Omán');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'PK', 'Pakistán');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'PW', 'Palau');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'PS', 'Palestina');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'PA', 'Panamá');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'PG', 'Papúa Nueva Guinea');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'PY', 'Paraguay');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'PE', 'Perú');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'PN', 'Pitcairn');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'PF', 'Polinesia Francesa');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'PL', 'Polonia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'PT', 'Portugal');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'PR', 'Puerto Rico');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'QA', 'Qatar');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'GB', 'Reino Unido');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CF', 'República Centroafricana');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'DO', 'República Dominicana');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'RE', 'Reunión');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'RW', 'Ruanda');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'RO', 'Rumanía');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'RU', 'Rusia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'EH', 'Sáhara Occidental');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'WS', 'Samoa');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'AS', 'Samoa Americana');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SM', 'San Marino');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'PM', 'St. Pierre y Miquelon');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SH', 'Santa Helena');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'KN', 'Saint Kitts y Nevis');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'LC', 'Santa Lucía');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'ST', 'Santo Tomé y Príncipe');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'VC', 'San Vicente y las Granadinas');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SN', 'Senegal');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CS', 'Serbia y Montenegro');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SC', 'Seychelles');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SL', 'Sierra Leona');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SG', 'Singapur');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SY', 'Siria');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SO', 'Somalia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'LK', 'Sri Lanka');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SZ', 'Suazilandia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'ZA', 'Sudáfrica');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SD', 'Sudán');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SE', 'Suecia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'CH', 'Suiza');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'SR', 'Surinam');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TH', 'Tailandia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TW', 'Taiwán');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TJ', 'Tayikistán');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TZ', 'Tanzania');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'IO', 'Territorio Británico del Océano Índico');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TF', 'Territorios Franceses del Sur');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TL', 'Timor Oriental');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TG', 'Togo');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TK', 'Tokelau');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TO', 'Tonga');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TT', 'Trinidad y Tobago');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TM', 'Turkmenistán');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TN', 'Túnez');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TR', 'Turquía');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'TV', 'Tuvalu');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'UA', 'Ucrania');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'UG', 'Uganda');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'UY', 'Uruguay');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'UZ', 'Uzbekistán');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'VU', 'Vanuatu');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'VE', 'Venezuela');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'VN', 'Vietnam');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'WF', 'Wallis y Futuna');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'YE', 'Yemen');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'ZM', 'Zambia');
INSERT INTO pance_paises (id, codigo_iso, nombre) VALUES (0, 'ZW', 'Zimbabue');
