<?php

/**
*
* Copyright (C) 2009 FELINUX Ltda
* Francisco J. Lozano B. <fjlozano@felinux.com.co>
* Mauricio Oidor L. <ozzymauricio75@gmail.com>
*
* Este archivo es parte de:
* PANCE :: Plataforma para la Administración del Nexo Cliente-Empresa
*
* Este programa es software libre: usted puede redistribuirlo y/o
* modificarlo  bajo los términos de la Licencia Pública General GNU
* publicada por la Fundación para el Software Libre, ya sea la versión 3
* de la Licencia, o (a su elección) cualquier versión posterior.
*
* Este programa se distribuye con la esperanza de que sea útil, pero
* SIN GARANTÍA ALGUNA; ni siquiera la garantía implícita MERCANTIL o
* de APTITUD PARA UN PROPÓSITO DETERMINADO. Consulte los detalles de
* la Licencia Pública General GNU para obtener una información más
* detallada.
*
* Debería haber recibido una copia de la Licencia Pública General GNU
* junto a este programa. En caso contrario, consulte:
* <http://www.gnu.org/licenses/>.
*
**/

$textos = array(
    "GESTREVI"                                   => "Reporte visitas",                                  
    "ADICREVI"                                   => "Generar cotización",                                 
    "CONSREVI"                                   => "Consultar reporte",                                 
    "MODIREVI"                                   => "Modificar reporte",                                 
    "ELIMREVI"                                   => "Eliminar reporte",  
    "VIOFREVI"                                   => "Visita sin oferta",
    "COTIZAR"                                    => "Cotizar requerimiento",
    "VISITAR"                                    => "Reporte visita",
    "id"                                         => "Código cotización", 
    "DESCRIPCION"                                => "Descripción",
    "EMPRESA"                                    => "Empresa",
    "SEDE"                                       => "Sede",
    "SUCURSAL"                                   => "Consorciado",  
    "MUNICIPIO"                                  => "Municipio",                                         
    "NOTIFICADO"                                 => "Notificado",       
    "TIPO_SOLICITUD"                             => "Tipo solicitud",                                            
    "OBSERVACIONES"                              => "Observaciones generadas por el cliente",                    
    "OBSERVACIONES_VISITA"                       => "Observaciones de la visita",                                
    "FECHA_VISITA"                               => "Fecha visita",    
    "FECHA_LIMITE_VISITA"                        => "Limite visita",    
    "FECHA_INGRESO"                              => "Fecha ingreso",
    "NUMERO_COTIZACION"                          => "Numero cotización",  
    "NUMERO_COTIZACION_CONSORCIADO"              => "Numero cotización consorciado",
    "GENERA_COTIZACION"                          => "Genera cotización",  
    "NO_GENERA_COTIZACION"                       => "No genera cotización",  
    "VALOR_REQUERIMIENTO"                        => "Valor requerimiento",
    "VALOR_MANO_OBRA_COTIZACION"                 => "Valor mano de obra",                                        
    "VALOR_MANO_OBRA_MODIFICADA"                 => "Valor mano de obra propuesta",                              
    "VALOR_MATERIALES_COTIZACION"                => "Valor materiales",                                          
    "VALOR_MATERIALES_MODIFICADOS"               => "Valor materiales propuesta",  
    "VALOR_ADMINISTRACION_COTIZACION"            => "Valor administración",
    "VALOR_IMPREVISTOS_COTIZACION"               => "Valor imprevistos",
    "VALOR_UTILIDAD"                             => "Valor utilidad",
    "VALOR_IMPUESTO"                             => "Valor impuesto",
    "VALOR_BASE_IMPUESTO"                        => "Base para impuesto",
    "SUB_TOTAL"                                  => "Sub-Total AIU",
    "TOTAL_GENERAL"                              => "Total general",
    "AYUDA_SUB_TOTAL"                            => "Sub-Total",
    "AYUDA_TOTAL_GENERAL"                        => "Total general",
    "PORCENTAJE_ADMINISTRACION_COTIZACION"       => "Porcentaje administración",
    "PORCENTAJE_IMPREVISTOS_COTIZACION"          => "Porcentaje imprevistos",                                                              
    "COSTO_DIRECTO"                              => "Costo directo",                                             
    "PORCENTAJE_UTILIDAD"                        => "Porcentaje utilidad",                                                                    
    "IMPUESTO"                                   => "Impuesto",                                                                                          
    "FORMA_PAGO"                                 => "Forma de pago",                                             
    "FORMA_PAGO_MODIFICADO"                      => "Forma de pago propuesta",                                   
    "PORCENTAJE_ANTICIPO"                        => "Porcentaje anticipo",                                       
    "PORCENTAJE_ANTICIPO_MODIFICADO"             => "Porcentaje anticipo propuesta",                             
    "PORCENTAJE_MANO_OBRA"                       => "Porcentaje mano obra",                                      
    "PORCENTAJE_MANO_OBRA_MODIFICADO"            => "Porcentaje mano obra propuesta",                            
    "PORCENTAJE_MATERIALES"                      => "Porcentaje materiales",                                     
    "PORCENTAJE_MATERIALES_MODIFICADO"           => "Porcentaje materiales propuesta",                           
    "FECHA_ENVIO"                                => "Fecha envío cotización",                                                    
    "NOMBRE_SEDE"                                => "Sede",                                                      
    "TERCERO"                                    => "Empresa",                                                   
    "NUMERO_COTIZACION"                          => "Numero cotización",                                         
    "PAGO_PARCIAL"                               => "Pago parcial",                                              
    "CONTRAENTREGA"                              => "Contra-Entrega",                                            
    "RAZON_SOCIAL"                               => "Razón social",                                              
    "CONTACTO"                                   => "Contacto",     
    "TELEFONO_CONTACTO"                          => "Telefono contacto",
    "CODIGO"                                     => "Código sede",                                               
    "SEDE"                                       => "Sede",                                                      
    "CARGO"                                      => "Cargo",                                                     
    "TIPO_SOLICITUD"                             => "Tipo solicitud",                                            
    "FECHA_INGRESO"                              => "Fecha ingreso",                                             
    "FECHA_ENVIO"                                => "Fecha envío",                                               
    "FECHA_INGRESO_SISTEMA"                      => "Fecha - hora confirmación",                                 
    "DESCRIPCION"                                => "Descripción ",                                                                                                 
    "OBSERVACIONES"                              => "Observaciones",                                             
    "CONFIRMADO"                                 => "Confirmada",                                                
    "NO_CONFIRMADO"                              => "No confirmada",                                             
    "COTIZADA"                                   => "Cotizar",                                                  
    "NO_COTIZADA"                                => "No cotizar",                                               
    "ESTADO"                                     => "Estado cotización",                                          
    "TELEFONO_PRINCIPAL"                         => "Teléfono principal",                                        
    "CELULAR"                                    => "Celular",                                                   
    "MANTENIMIENTO"                              => "Mantenimiento",                                             
    "EMERGENCIA"                                 => "Emergencia",                                                
    "SERVICIO"                                   => "Servicio por demanda",                                      
    "PROYECTO"                                   => "Proyecto", 
    "VISITA"                                     => "Visita",
    "ESTADO_COTIZACION_CLIENTE"                  => "Estado cotización",
    "AIU"                                        => "AIU",                                                       
    "NO_AIU"                                     => "No AIU",                                                    
    "NO_ENVIADA"                                 => "No enviada",                                                
    "ENVIADA"                                    => "Enviada",                                                   
    "CORREO_ELECTRONICO"                         => "Correo electrónico",
    "ESTADO_COTIZACION"                          => "Cotización",
    "PESTANA_GENERAL"                            => "Información general",                                       
    "PESTANA_REQUERIMIENTO"                      => "Información requerimiento",                                 
    "PESTANA_COTIZACION"                         => "Datos cotización",
    "PESTANA_VISITA"                             => "Datos visita",
    "PESTANA_DATOS_COTIZACION"                   => "Valores de cotizacion",
    "AYUDA_NUMERO_COTIZACION"                    => "Numero cotización",
    "AYUDA_NUMERO_COTIZACION_CONSORCIADO"        => "Numero cotización consorciado",
    "AYUDA_IMPUESTO"                             => "Valor del impuesto sobre la utilidad",
    "AYUDA_SUCURSAL"                             => "Sucursal asignada a la sede",                               
    "AYUDA_CODIGO"                               => "Código asignado a la sede",                                 
    "AYUDA_SEDE"                                 => "Sede que realizara la solicitud",                           
    "AYUDA_EMPRESA"                              => "Empresa del consorcio",                                     
    "AYUDA_FECHA_INGRESO"                        => "Fecha de solicitud del servicio",                           
    "AYUDA_FECHA_VISITA"                         => "Fecha visita",                                              
    "AYUDA_FECHA_ENVIO"                          => "Fecha envío de la cotización al cliente",                   
    "AYUDA_DESCRIPCION"                          => "Descripción del servicio",                                  
    "AYUDA_TIPO_SOLICITUD"                       => "Tipo de servicio solicitado",                               
    "AYUDA_SUCURSAL"                             => "Nombre de la sucursal del consorcio",                       
    "AYUDA_TERCERO"                              => "Empresa asignada al servicio",                              
    "AYUDA_CONTACTO"                             => "Persona a contactar",                                       
    "AYUDA_CARGO"                                => "Cargo que ocupa la persona a contactar",                    
    "AYUDA_OBSERVACIONES"                        => "Indicaciones adicionales dadas por el cliente",             
    "AYUDA_ESTADO"                               => "Estado de la solicitud",                                    
    "AYUDA_CORREO_ELECTRONICO"                   => "Correo electrónico de la persona a contactar",              
    "AYUDA_TELEFONO_PRINCIPAL"                   => "Teléfono principal de la persona a contactar",              
    "AYUDA_CELULAR"                              => "Numero celular de la persona a contactar",                  
    "AYUDA_OBSERVACIONES_VISITA"                 => "Observaciones hechas en la visita por el consorciado",              
    "AYUDA_VALOR_MANO_OBRA_COTIZACION"           => "Valor de la mano de obra del requerimiento",                
    "AYUDA_VALOR_MATERIALES_COTIZACION"          => "Valor de los materiales del requerimiento",                 
    "AYUDA_PORCENTAJE_ADMINISTRACION_COTIZACION" => "Porcentaje de Administración",
    "AYUDA_PORCENTAJE_IMPREVISTOS_COTIZACION"    => "Porcentaje de los imprevistos",
    "AYUDA_COSTO_DIRECTO"                        => "Costo directo requerimiento",
    "AYUDA_PORCENTAJE_UTILIDAD"                  => "Porcentaje de la utilidad",  
    "AYUDA_IMPUESTO"                             => "Porcentaje del impuesto sobre la utilidad",  
    "AYUDA_VALOR_ADMINISTRACION_COTIZACION"      => "Valor administración calculado",                                 
    "AYUDA_VALOR_IMPREVISTOS_COTIZACION"         => "Valor imprevistos calculado",
    "AYUDA_VALOR_UTILIDAD"                       => "Valor utilidad calculado",
    "AYUDA_VALOR_IMPUESTO"                       => "Valor impuesto calculado",
    "AYUDA_BASE_IMPUESTO"                        => "Valor base para calcular impuesto",
    "AYUDA_FORMA_PAGO"                           => "Forma de pago del requerimiento",                                     
    "AYUDA_PORCENTAJE_ANTICIPO"                  => "Porcentaje sobre el valor total para el anticipo",                    
    "AYUDA_PORCENTAJE_MANO_OBRA"                 => "Porcentaje correspondiente al consorciado por mano de obra",          
    "AYUDA_PORCENTAJE_MATERIALES"                => "Porcentaje correspondiente al consorciado por materiales",            
    "AYUDA_ESTADO_COTIZACION_CLIENTE"            => "Verificar que se envió al cliente la cotización",
    "ITEM_NO_COTIZAR"                            => "El requerimiento fue modificado",
    "ERROR_COTIZAR"                              => "Requerimiento ya fue cotizado............",
    "ERROR_NO_COTIZAR"                           => "El requerimiento no pudo ser modificado",
    "ERROR_MODIFICAR_COTIZAR"                    => "La cotización no ha sido generada o enviada al cliente",
    "ERROR_ELIMINAR_COTIZAR"                     => "La cotización no es posible eliminarla, por favor debe generarla",
    "ERROR_EXISTE_DESCRIPCION"                   => "Ya existe esa descripción del requerimiento",                         
    "ERROR_EXISTE_SEDE"                          => "Ya existe una sede con ese código",                                   
    "ERROR_EXISTE_NUMERO_COTIZACION"             => "Ya existe ese numero de cotización",                                  
    "ERROR_EXISTE_CONTACTO"                      => "Ya existe un contacto con ese nombre",                                
    "ERROR_EXISTE_CODIGO"                        => "Ya existe un requerimiento con ese código",                           
    "ERROR_FORMATO_NUMERO_COTIZACION"            => "El numero de la cotización debe contener solo números",               
    "ERROR_FORMATO_MANO_OBRA"                    => "El campo mano de obra debe contener solo números",                    
    "ERROR_FORMATO_MATERIALES"                   => "El campo materiales debe contener solo números",                      
    "ERROR_FORMATO_PORCENTAJE_ANTICIPO"          => "El campo anticipo debe contener solo números",                        
    "ERROR_FORMATO_PORCENTAJE_MANO_OBRA"         => "El campo porcentaje de la mano de obra debe contener solo números",   
    "ERROR_FORMATO_PORCENTAJE_MATERIALES"        => "El campo porcentaje materiales debe contener solo números",           
    "ERROR_FORMATO_ADMINISTRACION"               => "El campo valor administración debe contener solo números",            
    "ERROR_FORMATO_IMPREVISTOS"                  => "El campo imprevistos debe contener solo números",                     
    "ERROR_FORMATO_UTILIDAD"                     => "El campo utilidad debe contener solo números",                        
    "ERROR_FORMATO_IMPUESTO"                     => "El campo impuesto debe contener solo números",
    "ERROR_ESTADO_GENERA"                        => "Visita realizada",
    "APROBADA"                                   => "Aprobada",
    "NO_APROBADA"                                => "No aprobada",
    "PERSONA_RECIBE"                             => "Persona que recibe",
    "MEDIO_RECIBO"                               => "Medio",
    "CODIGO_CONTABLE"                            => "Código contable",
    "NUMERO_REQUERIMIENTO"                       => "Número requerimiento",
    "VISITA_SIN_OFERTA"                          => "No se requiere cotización",
    "REQUERIMIENTO_COTIZADO"                     => "Requerimiento ya fue cotizado",
);                                                                                                             
?>
